### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by smartdev328** [smart-tech-guru/monica-crm#15]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

While building this project on windows I've faced unknown errors

### Steps to reproduce

System: Windows
Node Version : 16.12.0

### Expected behavior

Need to build successfully

### Environment

app.monicahq.com (monica v4)

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by smart-tech-guru** [comment]
You need to use Latest Node Version.
